SELECT RDOCNUM, TRANNO, SACSCODE, SACSTYP,         
      BATCACTYR, BATCACTMN, BATCTRCDE, BATCBATCH,  
      ORIGAMT, ACCTAMT, GLSIGN FROM ISHAN/B522     
      WHERE GLSIGN <> '-'                          